import type { Message } from "@simulacra-ai/core";
import type { SessionMetadata, SessionStore } from "./types.ts";

type PrismaPromiseLike<T> = PromiseLike<T> | Promise<T>;

/**
 * The shape of a Prisma session model record.
 *
 * Define this model in your own Prisma schema, then pass the generated model
 * delegate (for example, `prisma.session`) to {@link PrismaSessionStore}. This
 * package intentionally does not import `@prisma/client`, so Prisma stays in
 * the consuming application's dependency graph instead of this package's.
 *
 * Example Prisma schema:
 * ```prisma
 * model Session {
 *   id         String   @id
 *   metadata   Json
 *   messages   Json
 *   updated_at DateTime
 * }
 * ```
 */
export type PrismaSessionRow = {
  id: string;
  /** JSON-serializable value storing `Omit<SessionMetadata, "id">`. */
  metadata: unknown;
  /** JSON-serializable value storing `Message[]`. */
  messages: unknown;
  /** Denormalized from metadata for efficient ORDER BY. */
  updated_at: Date | string;
};

/**
 * Structural subset of a generated Prisma model delegate.
 *
 * Use the delegate generated by your application, usually `prisma.session`.
 * Keeping this as a structural type avoids a runtime or installable dependency
 * on Prisma while still documenting the exact CRUD methods this store calls.
 */
export type PrismaSessionDelegate = {
  findMany(args: {
    select: { id: true; metadata: true; messages: true; updated_at: true };
    orderBy: { updated_at: "desc" };
  }): PrismaPromiseLike<PrismaSessionRow[]>;

  findUnique(args: {
    where: { id: string };
    select: { metadata: true; messages: true };
  }): PrismaPromiseLike<Pick<PrismaSessionRow, "metadata" | "messages"> | null>;

  upsert(args: {
    where: { id: string };
    create: PrismaSessionRow;
    update: Pick<PrismaSessionRow, "metadata" | "messages" | "updated_at">;
  }): PrismaPromiseLike<unknown>;

  deleteMany(args: { where: { id: string } }): PrismaPromiseLike<{ count: number }>;
};

/**
 * A database-backed implementation of `SessionStore` powered by Prisma Client.
 *
 * This store accepts a generated Prisma model delegate instead of importing
 * Prisma. That keeps this package dependency-free with respect to Prisma while
 * letting applications use their own generated client and schema.
 */
export class PrismaSessionStore implements SessionStore {
  readonly #delegate: PrismaSessionDelegate;

  constructor(delegate: PrismaSessionDelegate) {
    this.#delegate = delegate;
  }

  /**
   * Lists all sessions, sorted by most recently updated first.
   *
   * @returns A promise that resolves to an array of session metadata.
   */
  async list(): Promise<SessionMetadata[]> {
    const rows = await this.#delegate.findMany({
      select: { id: true, metadata: true, messages: true, updated_at: true },
      orderBy: { updated_at: "desc" },
    });

    return rows.map((row) => ({
      id: row.id,
      ...(row.metadata as Omit<SessionMetadata, "id">),
    }));
  }

  /**
   * Loads a session by its ID.
   *
   * @param id - The unique identifier of the session to load.
   * @returns A promise that resolves to the session metadata and messages, or undefined if not found.
   */
  async load(id: string): Promise<{ metadata: SessionMetadata; messages: Message[] } | undefined> {
    const row = await this.#delegate.findUnique({
      where: { id },
      select: { metadata: true, messages: true },
    });

    if (!row) {
      return undefined;
    }

    return {
      metadata: {
        id,
        ...(row.metadata as Omit<SessionMetadata, "id">),
      },
      messages: row.messages as Message[],
    };
  }

  /**
   * Saves a session with the given messages and metadata.
   *
   * Creates a new session if the ID does not exist, or updates the existing session.
   * Automatically updates the `updated_at` timestamp and `message_count`.
   *
   * @param id - The unique identifier of the session.
   * @param messages - The messages to store for this session.
   * @param metadata - Optional partial metadata to merge with existing metadata.
   * @returns A promise that resolves when the save operation is complete.
   */
  async save(id: string, messages: Message[], metadata?: Partial<SessionMetadata>): Promise<void> {
    const now = new Date().toISOString();
    const existing = await this.#delegate.findUnique({
      where: { id },
      select: { metadata: true, messages: true },
    });
    const existing_metadata = existing?.metadata as Partial<SessionMetadata> | undefined;

    const merged: Omit<SessionMetadata, "id"> = {
      ...existing_metadata,
      created_at: existing_metadata?.created_at ?? now,
      updated_at: now,
      message_count: messages.length,
      ...metadata,
    };

    const row: PrismaSessionRow = {
      id,
      metadata: merged,
      messages,
      updated_at: now,
    };

    await this.#delegate.upsert({
      where: { id },
      create: row,
      update: {
        metadata: row.metadata,
        messages: row.messages,
        updated_at: row.updated_at,
      },
    });
  }

  /**
   * Deletes a session by its ID.
   *
   * @param id - The unique identifier of the session to delete.
   * @returns A promise that resolves to true if the session was deleted, false if it was not found.
   */
  async delete(id: string): Promise<boolean> {
    const result = await this.#delegate.deleteMany({ where: { id } });
    return result.count > 0;
  }
}
